[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/Manahip/econia.git", subdir = "src/move/econia", rev = "6338efc5b93862fa141c2470d53418e9064d122d" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "99182f047dc0582f7568cb7142d207a09be4b2a6" }
LiquidSwapInterface = { git = "https://github.com/hippospace/hippo-aggregator.git", subdir = "interface/pontem", rev= "ef6b5beb0719f0ebaa9e8aeb52a4c2406d3ed7f4"}
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "209f9e7016effc7e293794e22d0a7ad860b57bbd" }

[addresses]
hippo_aggregator = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"

