[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "b118f1c2a1b5f7b8f446f88dc9ee489428f7b534" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "ce89b7d2c85d02c24e9f3e374eaf432b525d29aa" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "c6814be881c5a85dcc8483be758c368a3f67010d" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP" }
basiq = { local = "./interface/basiq-basiq" }
ditto-staking = { local = "./interface/ditto-research" }
tortuga-stub = { local = "./interface/tortuga" }

[addresses]
hippo_aggregator = "89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"
poster = "0x02"
poster_2 = "0x03"
