[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/Manahip/econia.git", subdir = "src/move/econia", rev = "67114e1f3aa9d1a978b24646d99307796b84d80b" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "e3df66f7e9044f81c3dc1ebc713db78143443560" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "e74926a4e12dbffa783fd7bfad79641ce3e2f6a0" }
Liquidswap = { local = "./interface/pontem-Liquidswap"}
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP"}
basiq = { local = "./interface/basiq-basiq"}

[addresses]
hippo_aggregator = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
poster = "0x02"
poster_2 = "0x03"