[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "b540957040ff821b9519e6bb16b05c5d82387944" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "e3df66f7e9044f81c3dc1ebc713db78143443560" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "e74926a4e12dbffa783fd7bfad79641ce3e2f6a0" }
Liquidswap = { local = "./interface/pontem-Liquidswap"}
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP"}
basiq = { local = "./interface/basiq-basiq"}

[addresses]
hippo_aggregator = "e56148c106146758a4172a7189cd8487f84997de6f6c2b3396106a8f82cb0c33"
poster = "0x02"
poster_2 = "0x03"