[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "34031842044a12726b73388d27145124ebb36387" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "3566b486ba340ebd9afc9f5208c8fe40a5157ed9" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "70e8603cd50e07e25ca200864db32f86f9491825" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP" }
basiq = { local = "./interface/basiq-basiq" }
ditto-staking = { local = "./interface/ditto-research" }
tortuga-stub = { local = "./interface/tortuga" }

[addresses]
hippo_aggregator = "89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"
poster = "0x02"
poster_2 = "0x03"
