[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "4eeb9e3fa7a8f5985b7d0e71ddf875d9a6f2b690" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "96d67b8c72a04b16bbccf8a1f868ef6b4e1e9a06" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "8a0d2f27d4d567b070697aa07325887df077a739" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP" }
basiq = { local = "./interface/basiq-basiq" }
#ditto-staking = { local = "./interface/ditto-research" }
tortuga-stub = { local = "./interface/tortuga" }

[addresses]
hippo_aggregator = "89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"
poster = "0x02"
poster_2 = "0x03"
