[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "dc3bc281bf1010429c284d805c9d55d12ee52d0f" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "fad0a11128dfdc72d2fae3f27d96535e377446dd" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
basiq = { local = "./interface/basiq-basiq" }
#ditto-staking = { local = "./interface/ditto-research" }
#tortuga = { local = "./interface/tortuga" }
Aptoswap = { local = "./interface/aptoswap" }
aux = { local = "./interface/aux"}

[addresses]
hippo_aggregator = "89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"
poster = "0x12"
poster_2 = "0x13"
