[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/Manahip/econia.git", subdir = "src/move/econia", rev = "6b7b915d611b3610d7a7343e6f40d924c074b58c" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "00525babf2012c54d21c96ad133b3589a83dea7a" }
LiquidSwapInterface = { git = "https://github.com/hippospace/hippo-aggregator.git", subdir = "interface/pontem", rev= "0b7b4964c66aa3d46be6147422af8be84b98679b"}
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "379a8d7532c94fc496bfd9102ac71bef046726eb" }

[addresses]
hippo_aggregator = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"

