[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies]
Econia = { git = "https://github.com/Manahip/econia.git", subdir = "src/move/econia", rev = "4015c95e67fed2a9a1cfdff35a6871a43a911fbc" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "3d4674d7834a05935d2a31e1ab57ef822b947eb5" }
LiquidSwapInterface = { git = "https://github.com/hippospace/hippo-aggregator.git", subdir = "interface/pontem", rev= "8c914b08e5a17f8a00427e9924d8c608a5814df4"}

[addresses]
hippo_aggregator = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"

