[package]
name = 'aux'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v0.3.9'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
aux = '0x8b7311d78d47e37d09435b8dc37c14afd977c5cfa74f974d45f0258d986eef53'
